const SUBJECTS = [
  "Toán",
  "Ngữ văn",
  "Tiếng Anh",
  "Vật lý",
  "Hóa học",
  "Sinh học",
  "Lịch sử",
  "Địa lý",
  "Giáo dục công dân",
  "Tin học",
  "Tiếng Pháp",
  "Tiếng Trung",
  "Tiếng Nhật",
  "Tiếng Hàn",
  "Tiếng Đức",
  "Âm nhạc",
  "Mỹ thuật",
  "Thể dục",
  "Toán cao cấp",
  "Vật lý đại cương",
  "Hóa học đại cương",
  "Lập trình",
  "Kế toán",
  "Kinh tế",
];

module.exports = SUBJECTS;
